/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutTicketsRouteImport } from './routes/_layout/tickets'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutNewOrderRouteImport } from './routes/_layout/new-order'
import { Route as LayoutKycRouteImport } from './routes/_layout/kyc'
import { Route as LayoutIrcRouteImport } from './routes/_layout/irc'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAddFundsRouteImport } from './routes/_layout/add-funds'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTicketsRoute = LayoutTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNewOrderRoute = LayoutNewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKycRoute = LayoutKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIrcRoute = LayoutIrcRouteImport.update({
  id: '/irc',
  path: '/irc',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAddFundsRoute = LayoutAddFundsRouteImport.update({
  id: '/add-funds',
  path: '/add-funds',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add-funds': typeof LayoutAddFundsRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/irc': typeof LayoutIrcRoute
  '/kyc': typeof LayoutKycRoute
  '/new-order': typeof LayoutNewOrderRoute
  '/orders': typeof LayoutOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/tickets': typeof LayoutTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add-funds': typeof LayoutAddFundsRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/irc': typeof LayoutIrcRoute
  '/kyc': typeof LayoutKycRoute
  '/new-order': typeof LayoutNewOrderRoute
  '/orders': typeof LayoutOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/tickets': typeof LayoutTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/add-funds': typeof LayoutAddFundsRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/irc': typeof LayoutIrcRoute
  '/_layout/kyc': typeof LayoutKycRoute
  '/_layout/new-order': typeof LayoutNewOrderRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tickets': typeof LayoutTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/add-funds'
    | '/admin'
    | '/dashboard'
    | '/irc'
    | '/kyc'
    | '/new-order'
    | '/orders'
    | '/settings'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/add-funds'
    | '/admin'
    | '/dashboard'
    | '/irc'
    | '/kyc'
    | '/new-order'
    | '/orders'
    | '/settings'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/add-funds'
    | '/_layout/admin'
    | '/_layout/dashboard'
    | '/_layout/irc'
    | '/_layout/kyc'
    | '/_layout/new-order'
    | '/_layout/orders'
    | '/_layout/settings'
    | '/_layout/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tickets': {
      id: '/_layout/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof LayoutTicketsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/new-order': {
      id: '/_layout/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof LayoutNewOrderRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kyc': {
      id: '/_layout/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof LayoutKycRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/irc': {
      id: '/_layout/irc'
      path: '/irc'
      fullPath: '/irc'
      preLoaderRoute: typeof LayoutIrcRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/add-funds': {
      id: '/_layout/add-funds'
      path: '/add-funds'
      fullPath: '/add-funds'
      preLoaderRoute: typeof LayoutAddFundsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAddFundsRoute: typeof LayoutAddFundsRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutIrcRoute: typeof LayoutIrcRoute
  LayoutKycRoute: typeof LayoutKycRoute
  LayoutNewOrderRoute: typeof LayoutNewOrderRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTicketsRoute: typeof LayoutTicketsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAddFundsRoute: LayoutAddFundsRoute,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutIrcRoute: LayoutIrcRoute,
  LayoutKycRoute: LayoutKycRoute,
  LayoutNewOrderRoute: LayoutNewOrderRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTicketsRoute: LayoutTicketsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
